AppCoder/urls.py
from django.contrib import admin
from django.urls import path
from AppCoder import views

#TODOS LOS URLS QUE SE USAN EN LA APLICACION PARA LOS DIFERENTES MODELS
urlpatterns = [
    path('', views.inicio,name="Inicio"),#
    path('estudiantes', views.estudianteForm,name="Estudiantes"),#ESTUDIANTES
    path('buscarEstudiante', views.buscarEstudianteX,name="BuscarEstudiante"),#ESTUDIANTES
    path('buscarEstudiantes', views.buscarEstudiantesTodos,name="BuscarEstudiantes"),#ESTUDIANTES
    path('cursos', views.cursoForm,name="Cursos"),#CURSOS
    path('buscarCursos', views.buscarCursosTodos,name="BuscarCursos"),#CURSOS
    path('buscarCurso', views.buscarCursoY,name="BuscarCurso"),#CURSOS
    path('profesores', views.profesorForm,name="Profesores"),#PROFESORES
    path('buscarProfesor', views.buscarProfesorZ,name="BuscarProfesor"),#PROFESORES
    path('buscarProfesores', views.buscarProfesoresTodos,name="BuscarProfesores"),#PROFESORES
    path('entregables', views.entregablesForm,name="Entregables"),#ENTREGABLES
    path('buscarEntregables', views.buscarEntregablesTodos,name="BuscarEntregables"),#ENTREGABLES
    path('buscarEntregable', views.buscarEntregableW,name="BuscarEntregable"),#ENTREGABLES
]

proyecto_django_lumaca/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppCoder/', include('AppCoder.urls')),
]

AppCoder/models.py
from django.db import models

# MODELS CON SUS RESPECTIVAS COLUMNAS

class Estudiante(models.Model):
    documento = models.CharField(max_length=10)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    telefono = models.CharField(max_length=30)



class Curso(models.Model):
    nombre = models.CharField(max_length=30)
    comision = models.IntegerField()

class Profesor(models.Model):
    documento = models.CharField(max_length=10)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    telefono = models.CharField(max_length=30)
    profesion = models.CharField(max_length=30)

class Entregable(models.Model):
    nombre = models.CharField(max_length=30)
    fecha_entrega = models.DateField()
    entregado = models.BooleanField()

AppCoder/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import Template, Context,loader
from AppCoder.models import Estudiante,Curso,Profesor,Entregable
from django.db import OperationalError, IntegrityError
from AppCoder.forms import EstudianteFormulario,CursoFormulario, ProfesorFormulario,EntregableFormulario

#FUNCIONES DE VALIDACION DE INGRESO DE DATOS, SI EXISTE EL MISMO RETORNA TRUE, SINO RETORNA FALSE
def existePersona(documento,que_persona):
   
    estudiante = Estudiante.objects.filter(documento=documento)
    profesor = Profesor.objects.filter(documento=documento)
    #SI ES ESTUDIANTE, VERIFICA SI EXISTE EN EL MODEL ESTUDIANTE
    if que_persona == "Est":
        if estudiante.exists():
            return True
        else:
            return False
    #SI NO ES ESTUDIANTE, VERIFICARA SI EXISTE EN EL MODEL PROFESOR
    else:
        if profesor.exists():
            return True
        else:
            return False
#VERIFICA EXISTENCIA DE LA COMISION DEL NUEVO CURSO A INGRESAR
def existeCurso(comision):
    curso = Curso.objects.filter(comision=comision)

    if curso.exists():
        return True
    else:
        return False

#FUNCIONES QUE RENDERIZAN LOS DIFERENTES FORMULARIOS
def inicio(req):
    return render(req,"inicio.html",{'active_page': 'inicio'})

#RENDERIZA FORMULARIO DE INGRESO DE ESTUDIANTE, ADEMAS DE REALIZAR EL INGRESO DEL MISMO
def estudianteForm(req):
 
    try:
       
        if req.method == 'POST':

            miFormulario = EstudianteFormulario(req.POST)

            if miFormulario.is_valid():

                informacion = miFormulario.cleaned_data
                if existePersona(informacion['documento'],"Est"):
                    return render(req, "Estudiantes/estudiantes.html", {"error_message": "Estudiante ya existe",'active_page': 'estudiantes'})
                else:
                    nuevo_estudiante = Estudiante(documento = informacion['documento'],nombre = informacion['nombre'],apellido = informacion['apellido'],email = informacion['email'],telefono = informacion['telefono'])
                    nuevo_estudiante.save()

                    return render(req, "Estudiantes/estudiantes.html", {"message": "Estudiante ingresado con éxito",'active_page': 'estudiantes'})
                
            else:
                return render(req, "Estudiantes/estudiantes.html", {"error_message": "Datos inválidos",'active_page': 'estudiantes'})
        
        else:

            miFormulario = EstudianteFormulario()

            return render(req, "Estudiantes/estudiantes.html", {"miFormulario": miFormulario,'active_page': 'estudiantes'})
    except OperationalError as e:
    # MANEJA ERRORES OPERATIVOS CON LA BASE DE DATOS
        return render(req, "Estudiantes/estudiantes.html", {'error_message':f"Ha ocurrido un error no controlado con la base de datos: {str(e)}",'active_page': 'estudiantes'})
    except IntegrityError as e:
    # MANEJA ERRORES DE INTEGRIDAD CON LA BASE DE DATOS
        return render(req, "Estudiantes/estudiantes.html", {'error_message':f"Ha ocurrido un error de integridad no controlado con la base de datos: {str(e)}",'active_page': 'estudiantes'})
    except ValueError as e:
    # MANEJA ERRORES DE VALOR
        return render(req, "Estudiantes/estudiantes.html", {'error_message':f"Se deben ingresar los datos: {str(e)}",'active_page': 'estudiantes'})
    except Exception as e:
    # CUALQUIERA OTRA EXCEPCIÓN NO CONTROLADA
        return render(req, "Estudiantes/estudiantes.html", {'error_message':f"Excepción no controlada: {str(e)}",'active_page': 'estudiantes'})

#RENDERIZA EL FORMULARIO DE CONSULTAS DE UN CIERTO ESTUDIANTE
def buscarEstudianteX(req):
    try:
        if req.method == 'GET':
            
            miFormulario = EstudianteFormulario(req.GET)
            if miFormulario.is_valid():
                
                informacion = miFormulario.cleaned_data

                documento = informacion["documento"]

                estudiante = Estudiante.objects.filter(documento=documento)

                return render(req, "Estudiantes/formConsultarEstudiante.html", {"miFormulario": miFormulario,"estudiantes": estudiante, 'active_page': 'estudiantes',"documento_label":documento})
        

            else:
                
                return render(req, "Estudiantes/formConsultarEstudiante.html", {"error_message": "Formulario no valido",'active_page': 'estudiantes'})  
        
        else:
            miFormulario = EstudianteFormulario()
            return render(req, "Estudiantes/formConsultarEstudiante.html", {"miFormulario": miFormulario,'active_page': 'estudiantes'})
    except OperationalError as e:
    # MANEJA ERRORES OPERATIVOS CON LA BASE DE DATOS
        return render(req, "Estudiantes/formConsultarEstudiante.html", {'error_message':f"Ha ocurrido un error no controlado con la base de datos: {str(e)}",'active_page': 'estudiantes'})
    except IntegrityError as e:
    # MANEJA ERRORES DE INTEGRIDAD CON LA BASE DE DATOS
        return render(req, "Estudiantes/formConsultarEstudiante.html", {'error_message':f"Ha ocurrido un error de integridad no controlado con la base de datos: {str(e)}",'active_page': 'estudiantes'})
    except ValueError as e:
    # MANEJA ERRORES DE VALOR
        return render(req, "Estudiantes/formConsultarEstudiante.html", {'error_message':f"Se deben ingresar los datos: {str(e)}",'active_page': 'estudiantes'})
    except Exception as e:
    # CUALQUIERA OTRA EXCEPCIÓN NO CONTROLADA
        return render(req, "Estudiantes/formConsultarEstudiante.html", {'error_message':f"Excepción no controlada: {str(e)}",'active_page': 'estudiantes'})

#RENDERIZA EL FORMULARIO DE CONSULTAS DE TODOS LOS ESTUDIANTES
def buscarEstudiantesTodos(req):
    try:
        if req.method == 'GET':
            
                miFormulario = EstudianteFormulario(req.GET)
                if miFormulario.is_valid():
                    estudiantes = Estudiante.objects.all()

                    return render(req, "Estudiantes/formConsultarTodosEstudiantes.html", {"miFormulario": miFormulario,"estudiantes": estudiantes, 'active_page': 'estudiantes'})
        

                else:
                
                    return render(req, "Estudiantes/formConsultarTodosEstudiantes.html", {"error_message": "Formulario no valido",'active_page': 'estudiantes'})  
        
        else:
            miFormulario = EstudianteFormulario()
            return render(req, "Estudiantes/formConsultarTodosEstudiantes.html", {"miFormulario": miFormulario,'active_page': 'estudiantes'})
    
    
    
    except OperationalError as e:
    # MANEJA ERRORES OPERATIVOS CON LA BASE DE DATOS
        return render(req, "Estudiantes/formConsultarTodosEstudiantes.html", {'error_message':f"Ha ocurrido un error no controlado con la base de datos: {str(e)}",'active_page': 'estudiantes'})
    except IntegrityError as e:
    # MANEJA ERRORES DE INTEGRIDAD CON LA BASE DE DATOS
        return render(req, "Estudiantes/formConsultarTodosEstudiantes.html", {'error_message':f"Ha ocurrido un error de integridad no controlado con la base de datos: {str(e)}",'active_page': 'estudiantes'})
    except ValueError as e:
    # MANEJA ERRORES DE VALOR
        return render(req, "Estudiantes/formConsultarTodosEstudiantes.html", {'error_message':f"Se deben ingresar los datos: {str(e)}",'active_page': 'estudiantes'})
    except Exception as e:
    # CUALQUIERA OTRA EXCEPCIÓN NO CONTROLADA
        return render(req, "Estudiantes/formConsultarTodosEstudiantes.html", {'error_message':f"Excepción no controlada: {str(e)}",'active_page': 'estudiantes'})

#RENDERIZA FORMULARIO DE INGRESO DE CURSO, ADEMAS DE REALIZAR EL INGRESO DEL MISMO
def cursoForm(req):
        try:
            
            if req.method == 'POST':

                miFormulario = CursoFormulario(req.POST)

                if miFormulario.is_valid():

                    informacion = miFormulario.cleaned_data
                    if existeCurso(informacion['comision']):
                        return render(req, "Cursos/cursos.html", {"error_message": "Curso con esta comisión ya existe",'active_page': 'cursos'})
                    else:
                        nuevo_curso = Curso(nombre = informacion['nombre'], comision = informacion['comision'])
                        nuevo_curso.save()

                        return render(req, "Cursos/cursos.html", {"message": "Curso ingresado con éxito",'active_page': 'cursos'})
                
                else:

                    return render(req, "Cursos/cursos.html", {"error_message": "Datos inválidos",'active_page': 'cursos'})
            
            else:

                miFormulario = CursoFormulario()

                return render(req, "Cursos/cursos.html", {"miFormulario": miFormulario,'active_page': 'cursos'})
        except OperationalError as e:
    # MANEJA ERRORES OPERATIVOS CON LA BASE DE DATOS
            return render(req, "Cursos/cursos.html", {'error_message':f"Ha ocurrido un error no controlado con la base de datos: {str(e)}",'active_page': 'cursos'})
        except IntegrityError as e:
    # MANEJA ERRORES DE INTEGRIDAD CON LA BASE DE DATOS
            return render(req, "Cursos/cursos.html", {'error_message':f"Ha ocurrido un error de integridad no controlado con la base de datos: {str(e)}",'active_page': 'cursos'})
        except ValueError as e:
    # MANEJA ERRORES DE VALOR
            return render(req, "Cursos/cursos.html", {'error_message':f"Se deben ingresar los datos: {str(e)}",'active_page': 'cursos'})
        except Exception as e:
    # CUALQUIERA OTRA EXCEPCIÓN NO CONTROLADA
            return render(req, "Cursos/cursos.html", {'error_message':f"Excepción no controlada: {str(e)}",'active_page': 'cursos'})

#RENDERIZA EL FORMULARIO DE CONSULTAS DE UN CIERTO CURSO SEGUN COMISION
def buscarCursoY(req):
    try:
        if req.method == 'GET':
            

AppCoder/templates/Entregables/entregables.html
{% extends "padre.html" %}
{% load static %}

{% block contenidoQueCambia %}
  <title>Entregables</title>
  <label class="etiquetaOpciones" for="opcionEtiqueta">Elige una opción: </label>
  <select id="opcionEntregables" onchange="opcionesEntregables()">
    <option value="ingresoEntregables">Ingresar</option>
    <option value="consultarEntregables">Consultar</option>
    <option value="buscarEntregables">Consultar todos</option>
  </select>
  <div class="page-content page-container" id="page-content">
    <div class="padding">
      <div class="row container d-flex justify-content-center">
        <div class="col-md-6 col-lg-4">
          <form id="FormIngresarEntregable" class="card" action="{% url 'Entregables' %}" method="POST">{% csrf_token %}
            <h5 class="card-title fw-400">Ingresar Entregable</h5>
            <div class="card-body">
              {% if error_message %}
                <p class="MensajeError">{{error_message}}</p>
                <a href="{% url 'Entregables' %}" class="btn btn-block btn-bold btn-primary">Volver</a>
              {% else %}
                {% if message %}
                  <p>{{message}}</p>
                  <a href="{% url 'Entregables' %}" class="btn btn-block btn-bold btn-primary">Volver</a>
                {% endif %}
              {% endif %}
              <div class="form-group">
                {{ miFormulario.nombre }}
              </div>
              <div class="form-group">
                {{ miFormulario.fecha_de_entrega }}
              </div>
              <div class="form-group">
                <label for="id_entregado" class="form-check-label">Corregido: </label>
                {{ miFormulario.entregado }}
              </div>
              <div class="form-group">
                {{ miFormulario.submit }}
              </div>
            </div>
          </form>
          <form id="FormConsultarEntregable" class="card" action="{% url 'BuscarEntregable' %}" method="GET" style="display: none;">
            <h5 id="tituloFormEst" class="card-title fw-400">Consultar entregable</h5>
            <div class="card-body">
              <div class="form-group">
                {{ miFormulario.fecha_de_entrega }}
              </div>
              <div class="form-group">
                {{ miFormulario.buscar }}
              </div>
            </div>
          </form>
          <form id="FormConsultarEntregablesTodos" class="card" action="{% url 'BuscarEntregables' %}" method="GET" style="display: none;">{% csrf_token %}
            <h5 id="tituloFormEst" class="card-title fw-400">Consultar entregables</h5>
            <div class="card-body">
              <div class="form-group">
                {{ miFormulario.buscar }}
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

AppCoder/templates/Entregables/formConsultarEntregable.html
{% extends "padre.html" %}
{% load static %}

{% block contenidoQueCambia %}
  <title>Consulta</title>
  <div class="page-content page-container" id="page-content"></div>
  <div class="padding">
    <div class="row container d-flex justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="FondoConsulta">
          <p>Entregables subidos el día: <strong>{{ fecha_entrega_label }}</strong></p>
          {% if error_message %}
            <p class="MensajeError">{{error_message}}</p>
          {% else %}
            {% if entregables %}
              <ul>
                {% for entregable in entregables %}
                  <li>
                    <strong>Nombre del entregable:</strong> {{entregable.nombre}} - <strong>Fecha:</strong> {{entregable.fecha_entrega}} - <strong>Corregido:</strong> {{entregable.entregado}}
                  </li>
                {% endfor %}
              </ul>
            {% else %}
              <p class="MensajeError">No se encontraron datos!</p>
            {% endif %}
          {% endif %}
          <a href="{% url 'Entregables' %}" class="btn btn-block btn-bold btn-primary">Volver</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

AppCoder/templates/Entregables/formConsultarTodosEntregables.html
{% extends "padre.html" %}
{% load static %}

{% block contenidoQueCambia %}
  <title>Consulta</title>
  <div class="page-content page-container" id="page-content"></div>
  <div class="padding">
    <div class="row container d-flex justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="FondoConsulta">
          {% if error_message %}
            <p class="MensajeError">{{error_message}}</p>
          {% else %}
            {% if entregables %}
              <ul>
                {% for entregable in entregables %}
                  <li>
                    <strong>Nombre del entregable:</strong> {{entregable.nombre}} - <strong>Fecha:</strong> {{entregable.fecha_entrega}} - <strong>Corregido:</strong> {{entregable.entregado}}
                  </li>
                {% endfor %}
              </ul>
            {% else %}
              <p class="MensajeError">No se encontraron datos!</p>
            {% endif %}
          {% endif %}
          <a href="{% url 'Entregables' %}" class="btn btn-block btn-bold btn-primary">Volver</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}